function process_condition_number(base_dir, example_name, export)
    % PROCESS_CONDITION_NUMBER Evaluates and plots the condition number of 
    % active CutFEM matrices for a given example.
    
    data_dir = fullfile(base_dir, char(example_name), 'data');
    
    fprintf('==================================================\n');
    fprintf('Analysing Example: %s\n', example_name);
    fprintf('==================================================\n');
    
    output_file = fullfile(data_dir, 'output.dat');
    if ~exist(output_file, 'file')
        fprintf('  [WARN] Data file not found for %s. Skipping.\n\n', example_name);
        return;
    end
    
    % 1. Parse output.dat to extract stabilisation parameters and mesh sizes
    fid = fopen(output_file, 'r');
    fgetl(fid); % Skip the filename_base header
    tau_line = fgetl(fid);
    taus = str2num(tau_line); %#ok<ST2NM>
    stab_cases = length(taus);
    
    raw_data = textscan(fid, '%f');
    fclose(fid);
    
    % Reshape based on known output format: [h, n_err, error(stab_cases)]
    num_cols = 2 + stab_cases;
    data = reshape(raw_data{1}, num_cols, [])';
    h_all = data(:, 1);
    
    % Determine the maximum possible number of exported matrices
    n_export = floor(length(h_all) / 1);
    h_vals = h_all(1:n_export);
    
    % Pre-allocate condition number array
    cond_nums = zeros(n_export, stab_cases);
    completed_refs = 0;
    
    % 2. Process Matrices
    for ref = 1:n_export
        fprintf('  Refinement level %d/%d (%d levels remaining)\n', ...
            ref, n_export, n_export - ref);
            
        level_successful = true;
        
        for stab = 1:stab_cases
            mat_filename = fullfile(data_dir, sprintf('%s_ref%d_stab%d_mat.dat', example_name, ref, stab));
            
            if ~exist(mat_filename, 'file')
                level_successful = false;
                continue;
            end
            
            % Load the COO text data generated by matlab::Export
            B = load(mat_filename);
            if isempty(B)
                level_successful = false;
                continue;
            end
            
            % Convert to sparse matrix and enforce numerical symmetry
            A_global = spconvert(B);
            A_global = 0.5 * (A_global + A_global');
            
            % Compress the matrix by isolating the active degrees of freedom
            % This prevents infinite condition numbers from structurally singular null spaces
            active_dofs = find(any(A_global, 2)); 
            A_active = A_global(active_dofs, active_dofs);
            
            % Estimate condition number on the active block
            cond_nums(ref, stab) = condest(A_active);
        end
        
        if ~level_successful
            break; % Stop processing if files are missing (e.g., reached the end of exported data)
        end
        completed_refs = ref;
    end
    
    fprintf('  Analysis complete for %s.\n\n', example_name);
    
    % 3. Calculate Rates and Plot
    if completed_refs > 0
        % Truncate the arrays to remove empty pre-allocated rows
        cond_nums_cropped = cond_nums(1:completed_refs, :);
        h_vals_cropped = h_vals(1:completed_refs);
        
        % Calculate asymptotic rates using your existing get_rates function
        skip_idx = floor(length(h_vals_cropped) / 2);
        
        if completed_refs > skip_idx + 1
            rates = get_rates(h_vals_cropped, cond_nums_cropped, skip_idx);
        else
            rates = NaN(stab_cases, 1);
        end
        
        % Visualise and export the results
        fig_filename = example_name + "_cond.pdf";
        reference_slopes = [-2]; % Plotting O(h^-2) growth line
        
        plot_cond(taus, cond_nums_cropped, h_vals_cropped, rates, fig_filename, reference_slopes, export);
    else
        fprintf('  [WARN] No valid refinement levels completed for %s. Skipping plot.\n\n', example_name);
    end
end